"""initial_clean_migration

Revision ID: 2dd4437a7aa1
Revises: 
Create Date: 2025-05-29 23:22:53.250356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd4437a7aa1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('nom_entreprise', sa.String(), nullable=False),
    sa.Column('forme_juridique', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('numero_tva', sa.String(), nullable=True),
    sa.Column('chiffre_affaires', sa.Float(), nullable=True),
    sa.Column('resultat', sa.Float(), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.Column('capital_social', sa.Float(), nullable=True),
    sa.Column('code_naf', sa.String(), nullable=True),
    sa.Column('libelle_code_naf', sa.String(), nullable=True),
    sa.Column('dirigeant_principal', sa.String(), nullable=True),
    sa.Column('dirigeants_json', sa.JSON(), nullable=True),
    sa.Column('statut', sa.Enum('PROSPECT', 'CONTACT', 'QUALIFICATION', 'NEGOCIATION', 'CLIENT', 'PERDU', name='statusenum'), nullable=True),
    sa.Column('score_prospection', sa.Float(), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details_complets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_siren'), 'companies', ['siren'], unique=True)
    op.create_index(op.f('ix_companies_siret'), 'companies', ['siret'], unique=False)
    op.create_table('entreprises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('siren', sa.String(length=9), nullable=False),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('nom_entreprise', sa.String(), nullable=False),
    sa.Column('forme_juridique', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('numero_tva', sa.String(), nullable=True),
    sa.Column('chiffre_affaires', sa.Float(), nullable=True),
    sa.Column('resultat', sa.Float(), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.Column('capital_social', sa.Float(), nullable=True),
    sa.Column('code_naf', sa.String(), nullable=True),
    sa.Column('libelle_code_naf', sa.String(), nullable=True),
    sa.Column('dirigeant_principal', sa.String(), nullable=True),
    sa.Column('dirigeants_json', sa.JSON(), nullable=True),
    sa.Column('statut', sa.Enum('PROSPECT', 'CONTACT', 'QUALIFICATION', 'NEGOCIATION', 'CLIENT', 'PERDU', name='statusenum'), nullable=True),
    sa.Column('score_prospection', sa.Float(), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details_complets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siren', name='uq_entreprise_siren')
    )
    op.create_index(op.f('ix_entreprises_siren'), 'entreprises', ['siren'], unique=True)
    op.create_index(op.f('ix_entreprises_siret'), 'entreprises', ['siret'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_entreprises_siret'), table_name='entreprises')
    op.drop_index(op.f('ix_entreprises_siren'), table_name='entreprises')
    op.drop_table('entreprises')
    op.drop_index(op.f('ix_companies_siret'), table_name='companies')
    op.drop_index(op.f('ix_companies_siren'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
