"""add_last_scraped_at_to_models

Revision ID: a994be59c6d7
Revises: 2dd4437a7aa1
Create Date: 2025-05-30 00:05:59.815254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a994be59c6d7'
down_revision: Union[str, None] = '2dd4437a7aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entreprises', sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entreprises', 'last_scraped_at')
    op.drop_column('companies', 'last_scraped_at')
    # ### end Alembic commands ###
